namespace Minsk.CodeAnalysis.Syntax
{
    public enum SyntaxKind{

        BadToken,
        EOFToken,
        WhiteSpaceToken,
        NumberToken, 
        PlusToken,
        MinusToken,
        StarToken,
        SlashToken,
        LParenToken,
        RParenToken,
        IdentifierToken,
        BangToken,
        PipePipeToken,
        EqualsEqualsToken,
        BangEqualsToken,
        AmpersandAmpersandToken,
        EqualsToken,
        LessOrEqualsToken,
        GreaterToken,
        GreaterOrEqualsToken,
        AmpersandToken,
        PipeToken,
        TildeToken,
        HatToken,
        LBraceToken,
        RBraceToken,
        LessToken,

        LiteralExpression,
        BinaryExpression,
        ParenthesizedExpression,
        UnaryExpression,
        NameExpression,
        AssignmentExpression,
        
        TrueKeyword,
        FalseKeyword,
        ElseKeyword,
        IfKeyword,
        WhileKeyword,
        ForKeyword,
        ToKeyword,
        LetKeyword,
        VarKeyword,
        
        CompilationUnit,
        BlockStatement,
        ExpressionStatement,
        VariableDeclaration,
        WhileStatement,
        ForStatement,
        IfStatement,
        
        
    }
}